# Generated by Django 4.1.7 on 2023-04-17 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=3000)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book_file', models.FileField(upload_to='book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['-created'], name='imagesapp_i_created_ea0906_idx'),
        ),
    ]
