# Generated by Django 4.1.7 on 2023-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='book_file',
            field=models.FileField(upload_to='book/%y/%m/%d'),
        ),
    ]
