# Generated by Django 4.1.8 on 2023-04-18 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imagesapp", "0002_alter_images_book_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="book_file",
        ),
    ]
